package dev.dotworld.ble.bluetooth.gatt

import dev.dotworld.ble.BuildConfig


const val ACTION_RECEIVED_STREETPASS =
	"${BuildConfig.LIBRARY_PACKAGE_NAME}.ACTION_RECEIVED_STREETPASS"
const val ACTION_RECEIVED_STATUS =
	"${BuildConfig.LIBRARY_PACKAGE_NAME}.ACTION_RECEIVED_STATUS"
const val DEVICE_DATA = "${BuildConfig.LIBRARY_PACKAGE_NAME}.DEVICE_DATA"
const val DEVICE_ADDRESS = "${BuildConfig.LIBRARY_PACKAGE_NAME}.DEVICE_ADDRESS"
const val SIGNAL_STRENGTH = "${BuildConfig.LIBRARY_PACKAGE_NAME}.SIGNAL_STRENGTH"
const val TRANSMISSION_POWER = "${BuildConfig.LIBRARY_PACKAGE_NAME}.TRANSMISSION_POWER"
const val CONNECTION_DATA = "${BuildConfig.LIBRARY_PACKAGE_NAME}.CONNECTION_DATA"

const val STREET_PASS = "${BuildConfig.LIBRARY_PACKAGE_NAME}.STREET_PASS"
const val STATUS = "${BuildConfig.LIBRARY_PACKAGE_NAME}.STATUS"

const val ACTION_DEVICE_PROCESSED = "${BuildConfig.LIBRARY_PACKAGE_NAME}.ACTION_DEVICE_PROCESSED"
const val ACTION_GATT_DISCONNECTED = "${BuildConfig.LIBRARY_PACKAGE_NAME}.ACTION_GATT_DISCONNECTED"
